FreeCAD/FreeCAD-render

renderers/Luxrender.py
ui/RenderSettings.ui

Allows to invoke Lux tools (console and UI) with predefined command line
parameters, set in Preferences (like for Appleseed, POV-ray, Cycles...)

[Render/Lux] Add command line parameters for Lux

---

renderers/Luxrender.py

Make Luxrender spawn in a distinct subprocess, so that FreeCAD remains
responsive during rendering.
By the way, it suppresses 'os.system' use, which seems deprecated in favor
of 'subprocess': https://docs.python.org/3.7/library/os.html#os.system

[Lux/Render] Make Luxrender call non-blocking

---

Render.py
renderers/Appleseed.py
renderers/Luxrender.py

Windows prevents you from deleting a file unless all handles are closed.
This resulted in an exception

Close handle returned by tempfile.mkstemp

---

Render.py
renderers/Appleseed.py
renderers/Cycles.py
renderers/Luxrender.py
renderers/Povray.py

This PR allows user to add Point Lights in a rendering scene, to be processed by the renderer.
For now, it's developed only for POV-Ray, but it will be extended to other renderers in a next step.
Usage:
Add a Point Light with Arch Texture workbench (set its color, position...)
Import the Point Light in your rendering project, via Render workbench
Render!
By the way, I also did some refactoring in the render.py module. In particular, I modified the code so that the renderer module is not imported when exporting each object, but only once when exporting the complete project (and I also added comments in the code).

Pointlights

---

Camera.py
Render.py
camera.py
icons/Raytrace_Camera.svg

This camera object allows to record a particular position of active Coin
camera and reuse it in rendering process.
Camera object can simply be inserted as a "view" in rendering projects,
like other rendered objects, and will thereby be exported to renderers.
Benefits for users are:
- User can easily access Camera settings for validation and tweaking.
- Camera object has a graphical representation that helps user see
where Camera is and where it looks to
- User can create as many Cameras as he/she wishes, to record various
points of views and consequently reuse them in rendering.
- User can reset active Coin camera back to any Camera object position,
in order to retrieve previous points of views
- User can opt to have no Camera in a given project: in that case, the
active Coin camera …

Add a Camera object

---

renderers/Povray.py

The "Output Image" setting appears to be ignored.
The file is being saved to a system temp directory such as:
/var/folders/...
I could not find where the file is copied to the "Output Image".
This commit checks if there is an output file specified
and uses it if it is.

Fix image output

---

renderers/Appleseed.py

Appleseed: fix unescaped '\t' in mesh temp file path

---

Render.py

With this PR, it is possible to import a FreeCAD group into a rendering project in a one-click action. The group is recreated in the rendering project.
This PR proposes also a better toponymy for views in rendering projects (namely: object@project)

Add support for groups in rendering projects and improve view naming

---

Render.py

Temporarily disables visibility support (commit 8f02cb15a9cdec2324fead14ccdd3c3103534e21), as it causes an issue with version 0.18

Visibility: revert to previous functioning due to issue with v0.18

---

Render.py

Object Visibility awareness in rendering had been disabled due to a compatibility issue with version 0.18. This commit restores it and fixes the issue with version 0.18

Restore Visibility awareness in rendering

---

rendermaterials.py

Make lru_cache calls compatible with previous versions of Python (<=3.7)

---

Render.py

Otherwise ArchMaterial tries to set a ShapeColor on ViewProviderView, which raises an error...

Materials: set UseMaterialColor to False on ViewProviderView

---

Render/renderables.py

Otherwise we may have an immutable object and further treatments
(rescaling...) will fail.

Renderables: make a copy of mesh for Mesh::Feature

---

Render/lights.py

This reverts commit 0c90d6057e62fb79a3860969923fe7a89f3a0559.
Reason: Side-effect when converting an old light (previous location is erased)

Revert "Lights: add a (replicated) Placement property in Point Light"

---

Render/lights.py

2nd try: Placement property is no more created for old instances

Lights: add a (replicated) Placement property in Point Light (2nd try)

---

Render/renderers/Pbrt.py

'tint' parameter was removed by pbrt's developper, so we cannot export
it anymore.

Pbrt: remove 'tint' parameter in mixed material export

---

Render/rdrhandler.py

ref: [https://forum.freecadweb.org/viewtopic.php?style=4&f=10&t=69321](https://forum.freecadweb.org/viewtopic.php?style=4&f=10&t=69321)
Scripted objects can create/set arbitrary attributes in their Proxy
objects. Formerly, if an object's Proxy had a 'type' attribute, it would
be used to determine which Rendering Handler should be used. This behavior
caused errors e.g. for FastenersWB objects, which used the type param
to indicate the specification of a fastener.
This commit changes the behavior of the get_rendering_string function
to check if an object needs a specific handler using the Proxy's python type.
The example file in the linked forum post now works properly with this fix.

get_rendering_string: don't use 'source.Proxy.type' attr to choose RenderHandler

---

Render/rdrhandler.py

Always cast object's RENDERING_TYPE to RenderingTypes (to avoid sporadic ValueError)

RendererHandler: fix ValueError bug with RenderingTypes

---

Render/renderers/Luxcore.py

The LuxCore renderer's field of view setting applies to the largest image dimension. Currently the vertical fov used by FreeCAD is converted to a horizontal fov for use by LuxCore. For typical images where the width is larger than the height this is fine. However, when rendering an image with width less than height (aspect ratio below 1) this causes the wrong fov to be passed to LuxCore.
I added an if statement to check the aspect ratio and make sure the correct fov is passed.

Bugfix for field of view when using LuxCore with aspect ratio < 1

---

Render/resources/ui/RenderSettings.ui

(name collisions would have occured with other workbenches UI)

RenderSettings: rename 'label' QLabel to avoid name collisions

---

templates/cycles_flat.xml
templates/cycles_standard.xml
templates/cycles_studio_dark.xml
templates/cycles_studio_light.xml
templates/cycles_sunlight.xml

Light trees were introduced recently. Without further adaptions, they prevent to use more than one light in a scene. For now, we disable, they may be reenabled later (but there will be a compatibility issue).

Cycles: disable "use light tree"

---

Render/material.py
Render/resources/ui/RenderSettings.ui

Inherited process from Arch Material automatically modifies ShapeColor when material is applied to object. This commit allows to control this behavior via a parameter.

Material: add setting to control shapecolor modification

---

Render/utils.py

At startup if we switch to the Render workbench while no document has been open, the initialization of the workbench fails and leave the it in an unusable state.
This change only make sure that there is an ActiveDocument before using it

Avoid initialization error when no document open.

---

Render/material.py
Render/taskpanels.py

Remove 'eval' use (security hole)

Passthrough: securize force_uvmap evaluation

---

Render/rendermaterial.py

Handle case when rendertex_bump.scalar is None

RenderMaterial: fix bug in get_bump_factor

---

Render/renderables.py

This is a fix for #351 where the rendering fails if the material used for a solid is not of the type `Render.Material`.
In my case the material is of type `Arch.ArchMaterial._ArchMaterial`.
It simply return `False` when the `material.proxy.has_textures()` is undefined.

Do not break on non Render Materials

---

Render/rdrhandler.py
Render/renderables.py
Render/rendermesh.py

1°) App::Part rendering was filtering on mesh.countpoint, which is not convenient for skipping meshes
2°) Missing meshing files were not handled while skipping (can be caused by empty topology at first meshing)

Fix several bugs related to skip meshing

---

Render/subcontainer.py

As mentioned [here](https://github.com/FreeCAD/FreeCAD-render/commit/a25677115687697a1f299bf535f0880f2e51a3c5#commitcomment-146072797)  and [this wiki](https://wiki.freecad.org/PySide#:~:text=Normally%2C%20the%20PySide%20module%20provides,of%20FreeCAD%20compiled%20for%20Qt5.) there is an error with PySide Module with PySide.QtWidgets:
> The only unusual aspect is that the PySide2.QtWidgets classes are placed in the PySide.QtGui namespace.

Remove No module named 'PySide.QtWidgets' error in earlier versions of FreeCAD
