FreeCAD/FreeCAD-render

renderers/Appleseed.py
The correct coordinate system is important if you use the sun's phi (azimuthal) and theta (polar) angles.
=> Fix for appleseed coordinate system

Render.py, renderers/Luxrender.py, templates/luxrender_flat.lxs, templates/luxrender_standard.lxs
Add also a 'flat' template for Lux, with no pre-defined light and a few tweaks (like no tone mapping), and make some refactoring in Luxrender.py
=> Add PointLight support for LuxCore renderer

renderers/Appleseed.py
Point light support in Appleseed renderer module was still in TODO status. This PR provides the missing code...
=> Appleseed: add point light support

renderers/Appleseed.py
- Fix an issue regarding cameras' aspect ratios (distorted rendering)
- Make Camera support effective
=> Appleseed: fix and improve Camera support

Render.py
This PR suppresses 'no-self-use' PEP8 non-compliance for Project.render method. 
This is achieved by removing the FeaturePython argument from the method signature. The related FeaturePython object is registered as a property of the Project when the Project is created/restored (managed as a class property, in order to avoid a serialization problem).
=> Linting: Suppress 'no self use' in Project.render

Render.py, icons/PointLight.svg, lights.py, pylintrc
This PR creates lights.py, a module with various lights objects to illuminate rendering scene. For now, this first version contains only a PointLight object, but is a basement to be extended to AreaLight, Image-Based Lighting and Hosek-WIlkie Skylight.
=> Creates lights.py

Render.py
If an object is not visible (Visibility==False), it won't be rendered
=> Take object visibility into account in rendering

renderers/Appleseed.py, renderers/Cycles.py, renderers/Luxrender.py, renderers/Povray.py, renderers/README.md
Add a README in the renderers repository, in order to explain how renderers plug-ins work and how they can be implemented
=> Renderers README

Render.py
Write _render_* methods in EAFP, suppress view arg to _call_renderer
=> Small refactoring in RendererHandler private methods

Render.py, renderers/Appleseed.py, renderers/Cycles.py, renderers/Luxrender.py, renderers/Povray.py
...instead, pass a FreeCAD.Base.Placement object (embedding both center and
rotation...)
=> Suppress rotation in write_camera parameters

Render.py, renderers/Appleseed.py, renderers/Cycles.py, renderers/Luxrender.py, renderers/Povray.py
Add newline to messages passed to FreeCAD.Console.Print*
=> Small linting

renderers/Luxrender.py
Area light efficency and gain had been wrongly set 10 times too high...
=> Luxrender: tune area light efficency and gain

Render.py
Previous version took only first-level views for ground plane
calculation (boundbox calculation). This commit allows to take account of all views
with recursive traversal of the projects.
=> Ground plane: take all views (recursive)

Render.py, renderables.py, renderers/Appleseed.py, rendermaterials.py, renderutils.py
Several fixes following various tests
=> Materials - bugs fixes

Render.py
Source property can be set to App::PropertyXLink in order to link to
source objects from external documents. In order to preserve some kind
of compatibility with FreeCAD 0.18, this setting will be reserved to this case only
(source object outside document). In other cases, the Source property
type will fall back to plain old App::PropertyLink.
=> Restrain XLink use in Views to external source objects only

README.md, Render.py, renderables.py, rendererhandler.py, rendermaterials.py, renderutils.py
Error (too early, this PR was just intended to assembly4 branch)
=> Revert "Assembly4 - adjustments for v0.18"

README.md, Render.py, renderables.py, rendererhandler.py, rendermaterials.py, renderutils.py
Reverts FreeCAD/FreeCAD-render#97
=> Revert "Revert "Assembly4 - adjustments for v0.18""

camera.py
...when reading from Coin string. It seems that those parameters could be lacking sometimes.
=> Camera: introduce default values for AspectRatio and ViewportMapping

Render.py, docs/Materials.md, icons/ApplyMaterial.svg, icons/Arch_Material_Group.svg, renderables.py
... making possible to add a Material to an object which has no pre-existing material property
=> Materials: add Material applier

Render.py, rendererhandler.py
Ground plane is no more treated as a temporary object added to document and then deleted (which implied recomputation and was not very efficient). Instead, the mesh is computed and translated directly in SDL by rendererhandler.
=> Avoid document recomputation in ground plane generation

Render.py, docs/Projects.md, rendererhandler.py, renderers/Appleseed.py, renderers/Cycles.py, renderers/Luxcore.py, renderers/Luxrender.py, renderers/Ospray.py, renderers/Povray.py, renderers/README.md
=> Projects: relative path for Template

Render/__init__.py, Render/base.py, Render/camera.py, Render/coin.py, Render/lights.py, Render/project.py, Render/utils.py, Render/view.py, pylintrc
Reorganize code in a more modular fashion.
=> Reorganize

Render/renderers/Luxcore.py, Render/resources/ui/RenderSettings.ui
This reverts commit 1c03c56b55a7ac0a6fc645733851878094deff01, reversing
changes made to 2ca9e423d0759002706d1d5953e77c8554d86189.
=> Revert "Merge pull request #159 from jphigham/luxcore-lib-path"

Render/base.py, Render/commands.py, Render/project.py, Render/renderers/Appleseed.py, Render/renderers/Luxrender.py, Render/renderers/Ospray.py, Render/taskpanels.py
Remove unnecessary computations (merge)
=> Remove unnecessary computations (merge)

Render/base.py, Render/project.py, Render/rdrhandler.py, Render/utils.py
Required by v0.20 to activate Placement feature on those objects
=> Base AreaLight and Camera on GeometryPython

Render/base.py, Render/lights.py, Render/renderers/Luxcore.py, Render/renderers/Luxrender.py
...so that one can use Placement and Transform tools on them
=> Add underlying Placement to Point Lights

Render/camera.py, Render/lights.py, Render/rdrhandler.py, Render/renderables.py, package.xml
...keeping compatibility with ArchTexture
=> Hotfix: get_rendering_string for Fasteners WB

Render/constants.py
Fix https://github.com/FreeCAD/FreeCAD-render/issues/197
=> Fix FCDVERSION invalid litteral for int ('19.4')

Render/renderers/Ospray.py
Not fully working, it lacks a patch on osp side...
=> Ospray: get output from osp

Render/renderables.py, Render/rendermesh.py, package.xml
=> Renderables: fix bugs related to _Transformation

Render/rendermaterial.py
This reverts commit 85615bc923d3ff336ebf9135345683a9fcde1037.
=> Revert "Renderables: fix bug in fallback material"

README.md
=> README: Remove LGTM badge

Render/rendermesh.py
Including _vnormals and _uvmap
Issue #286
=> Rendermesh: create all attributes while skip meshing

Render/constants.py, Render/material.py, materials/Aluminium.FCMat, materials/Brass.FCMat, materials/Carpaint.FCMat, materials/Glass.FCMat, materials/GlossyPlastic.FCMat, materials/Gold.FCMat, materials/GreenMarble.FCMat, materials/Iron.FCMat, materials/Matte.FCMat, materials/RoughPlastic.FCMat, materials/Terrazzo.FCMat
Render Materials are now recognized by 0.22 material system, but the material values are not imported yet.
=> Materials: partially implement 0.22 compatibility

Render/project.py, Render/utils.py
=> Fix App::Part link view duplication

Render/material.py
[See issue #327](https://github.com/FreeCAD/FreeCAD-render/issues/327)
=> Fix issue #327

README.md, Render/commands.py
This conserves the results from https://forum.freecad.org/viewtopic.php?t=88268
=> Add a FAQ section and a 1th FAQ to README.md

docs/EngineInstall.md
Improve doc, as discussed in #456
=> Doc, engine install: Add more obvious links to FAQ/bugs related sections
